name: Deploy to AWS EC2

on:
  workflow_run:
    workflows: ["Django CI"]  # Name of the CI workflow
    types:
      - completed
    status: success  # Only trigger if the CI workflow is successful

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Pull Docker Image and Restart Container
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        docker pull mustafataha5/my-django:latest
        docker stop django-app || true
        docker rm django-app || true
        docker run -d --name django-app -p 8000:8000 mustafataha5/my-django:latest
        EOF
